import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('@claim:demo-isolation sample data is isolated, resettable, and discardable', async ({ page }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Create job' }).click(); await page.getByLabel('Job name').fill('My real job'); await page.getByLabel('Agreed total').fill('100'); await page.getByRole('button', { name: 'Create job' }).last().click(); await expect(page.getByRole('heading', { name: 'My real job' })).toBeVisible(); await page.goto('/?demo=1'); await expect(page).toHaveURL(/\/demo$/); await expect(page.getByText('Demo — sample data, nothing is saved to your ledger')).toBeVisible(); await expect(page.getByText('Northstar brand handoff')).toBeVisible();
  const databases = await page.evaluate(async () => (await indexedDB.databases()).map(db => db.name)); expect(databases).toContain('release-ledger'); expect(databases).toContain('demo:release-ledger'); await page.getByRole('button', { name: 'Reset demo' }).click(); await expect(page.locator('#toast')).toContainText('Demo reset'); await page.getByRole('button', { name: 'Start for real' }).click(); await expect(page).toHaveURL(/\/$/); await expect(page.getByText('My real job')).toBeVisible(); await expect(page.getByText('Northstar brand handoff')).toHaveCount(0);
});

test('@claim:browser-privacy demo uses no account, bank, analytics, or remote data request', async ({ page }) => {
  const requests: string[] = []; page.on('request', request => requests.push(request.url())); await page.goto('/demo'); await page.getByRole('link', { name: /Harbor website launch/ }).click(); await page.getByRole('button', { name: 'Record entry' }).first().click(); await page.getByLabel('Amount (USD)').fill('10'); await page.getByRole('button', { name: 'Save entry' }).click(); expect(requests.every(url => new URL(url).origin === 'http://127.0.0.1:4173')).toBe(true); expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([]); await page.goto('/'); await expect(page.getByText('No account')).toBeVisible(); await expect(page.getByText(/does not hold funds, connect to a bank, process payments/)).toBeVisible();
});

test('@claim:offline-reload demo and sample records reopen offline after the first visit', async ({ page, context }) => {
  await page.goto('/demo'); await page.evaluate(async () => { await navigator.serviceWorker.ready; }); await page.reload(); await page.goto('/demo/jobs/demo-brand'); await expect(page.getByRole('heading', { name: 'Northstar brand handoff' })).toBeVisible(); await context.setOffline(true); await page.reload(); await expect(page.getByRole('heading', { name: 'Northstar brand handoff' })).toBeVisible(); await expect(page.getByText(/Offline — saved records/)).toBeVisible();
});

test('@claim:data-export exports all JSON and CSV data plus a filtered job CSV', async ({ page }) => {
  await page.goto('/demo'); let promised = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export backup' }).click(); let stream = await (await promised).createReadStream(); let bytes = Buffer.concat(await stream.toArray()).toString(); const backup = JSON.parse(bytes); expect(backup.jobs).toHaveLength(3); expect(backup.events).toHaveLength(10);
  await page.locator('#import-file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)) }); await expect(page.locator('#toast')).toContainText('Imported 3 jobs and 10 entries.');
  promised = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export CSV' }).click(); stream = await (await promised).createReadStream(); bytes = Buffer.concat(await stream.toArray()).toString(); expect(bytes).toContain('Northstar brand handoff'); expect(bytes).toContain('Harbor website launch'); await page.getByRole('link', { name: /Northstar brand handoff/ }).click(); promised = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export this job' }).click(); stream = await (await promised).createReadStream(); bytes = Buffer.concat(await stream.toArray()).toString(); expect(bytes).toContain('Northstar brand handoff'); expect(bytes).not.toContain('Harbor website launch');
});

test('@claim:release-status computes totals, all entry types, and unsafe over-release', async ({ page }) => {
  await page.goto('/demo/jobs/demo-packaging'); for (const label of ['Deposit received', 'Milestone ready', 'Release decision', 'Refund sent', 'Balance payment']) await expect(page.locator('.event-copy strong', { hasText: label })).toBeVisible(); await expect(page.locator('.balance-grid').getByText('$300.00', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Record entry' }).first().click(); await page.getByLabel('Entry type').selectOption('release'); await page.getByLabel('Amount (USD)').fill('1000'); await page.getByLabel('Ready').check(); await page.getByRole('button', { name: 'Save entry' }).click(); await expect(page.getByRole('heading', { name: 'Hold release' })).toBeVisible(); await expect(page.getByText(/released beyond recorded payments or finished work/)).toBeVisible();
});

test('@claim:client-receipt shows configured details and invokes print or PDF', async ({ page }) => {
  await page.goto('/demo/receipt/demo-brand'); await expect(page.getByText('Juniper Field Studio')).toBeVisible(); await expect(page.getByText('NS-204')).toBeVisible(); await expect(page.getByText('Sales tax')).toBeVisible(); await expect(page.getByText('Final source files follow the signed handoff note.')).toBeVisible(); let printed = false; await page.exposeFunction('claimPrint', () => { printed = true; }); await page.evaluate(() => { window.print = () => { void (window as unknown as { claimPrint: () => Promise<void> }).claimPrint(); }; }); await page.getByRole('button', { name: 'Print or save PDF' }).click(); await expect.poll(() => printed).toBe(true);
});

test('@claim:accessible-responsive supports keyboard, themes, legal routes, and 390px layout', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/'); await page.keyboard.press('Tab'); await expect(page.getByRole('link', { name: 'Skip to main content' })).toBeFocused(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); for (const element of await page.locator('header a:visible, header button:visible, footer a:visible').all()) { const box = await element.boundingBox(); expect(box?.height).toBeGreaterThanOrEqual(44); } await page.getByRole('button', { name: 'Switch color theme' }).click(); expect(await page.locator('html').getAttribute('data-theme')).toBeTruthy(); await page.goto('/privacy'); await expect(page).toHaveTitle('Privacy — Release Ledger'); await page.goto('/terms'); await expect(page).toHaveTitle('Terms — Release Ledger'); const axe = await new AxeBuilder({ page }).analyze(); expect(axe.violations.filter(v => ['serious', 'critical'].includes(v.impact ?? ''))).toEqual([]);
});
