import './styles.css';
import { calculateTotals, formatMoney, MAX_AMOUNT } from './calculations';
import { rowsToCsv } from './csv';
import { createBackup, discardDemo, getEvents, getJob, getJobs, getSettings, importBackup, isDemoMode, saveEvent, saveJob, seedDemo } from './db';
import type { AppSettings, EventType, Job, LedgerEvent, ReleaseDecision } from './types';

const app = document.querySelector<HTMLDivElement>('#app')!;
const toast = document.querySelector<HTMLElement>('#toast')!;
const routeStatus = document.querySelector<HTMLElement>('#route-status')!;
if (!app || !toast || !routeStatus) throw new Error('Application mount was not found.');
const ORIGIN = 'https://retainer-release-ledger.sociobot.in';
let storageError = '';
let toastTimer = 0;

const eventLabels: Record<EventType, string> = { deposit: 'Deposit received', milestone: 'Milestone ready', release: 'Release decision', refund: 'Refund sent', balance: 'Balance payment' };
const icon = (name: 'gate' | 'plus' | 'arrow' | 'download' | 'moon') => {
  const paths = { gate: '<path d="M6 21V5m12 16V5M4 5h16M8 8h8v10H8z"/>', plus: '<path d="M12 5v14M5 12h14"/>', arrow: '<path d="m9 18 6-6-6-6"/>', download: '<path d="M12 3v12m0 0 5-5m-5 5-5-5M5 21h14"/>', moon: '<path d="M20 15.2A8 8 0 1 1 8.8 4 6.5 6.5 0 0 0 20 15.2Z"/>' };
  return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]}</svg>`;
};
function escapeHtml(value: string | number): string { return String(value).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c] ?? c); }
function appPath(path: string): string { return !isDemoMode ? path : path === '/' ? '/demo' : `/demo${path}`; }
function isDemoPath(path: string): boolean { return path === '/demo' || path.startsWith('/demo/') || new URL(path, location.origin).searchParams.get('demo') === '1'; }

function shell(content: string): string {
  return `${isDemoMode ? `<aside class="demo-banner" aria-label="Demo mode"><strong>Demo — sample data, nothing is saved to your ledger</strong><span><button id="reset-demo" type="button">Reset demo</button><button id="start-real" type="button">Start for real</button></span></aside>` : ''}
  <header class="site-header"><a class="brand route-link" href="${appPath('/')}" aria-label="Release Ledger home"><span class="brand-mark">${icon('gate')}</span><span>Release <i>Ledger</i></span></a><nav aria-label="Primary"><a class="route-link nav-link" href="${appPath('/')}">Jobs</a><a class="route-link nav-link" href="/demo">Demo</a><a class="route-link nav-link" href="/privacy">Privacy</a><button class="icon-button" id="theme-toggle" type="button" aria-label="Switch color theme">${icon('moon')}</button></nav></header>
  <div class="network-banner" id="network-banner" role="status" ${navigator.onLine ? 'hidden' : ''}>Offline — saved records are available on this device.</div>${storageError ? `<div class="error-banner" role="alert">${escapeHtml(storageError)}</div>` : ''}${content}
  <footer class="site-footer"><p>Compare client payments with finished work before sending files.</p><nav aria-label="Footer"><a class="route-link" href="/privacy">Privacy</a><a class="route-link" href="/terms">Terms</a><a href="https://sociobot.in">Built by Param Factory <span class="visually-hidden">(external site)</span></a></nav><p class="provenance">Build polish-2 · Hero artwork was generated for this product.</p></footer>`;
}
function routeParts(): string[] { const parts = location.pathname.replace(/\/+$/, '').split('/').filter(Boolean); if (parts[0] === 'demo') parts.shift(); return parts; }
function setMeta(title: string, description: string, canonicalPath: string): void {
  document.title = title; const canonical = `${ORIGIN}${canonicalPath}`;
  const values: Record<string, string> = { 'meta[name="description"]': description, 'meta[property="og:title"]': title, 'meta[property="og:description"]': description, 'meta[property="og:url"]': canonical, 'meta[name="twitter:title"]': title, 'meta[name="twitter:description"]': description };
  Object.entries(values).forEach(([selector, value]) => document.querySelector<HTMLMetaElement>(selector)?.setAttribute('content', value));
  document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.setAttribute('href', canonical);
}

async function render(focusHeading = false): Promise<void> {
  try {
    await seedDemo(); const parts = routeParts(); const [first, id] = parts;
    if (!first) await renderHome(); else if (first === 'jobs' && id && parts.length === 2) await renderJob(id); else if (first === 'receipt' && id && parts.length === 2) await renderReceipt(id); else if (!isDemoMode && first === 'privacy' && parts.length === 1) renderPrivacy(); else if (!isDemoMode && first === 'terms' && parts.length === 1) renderTerms(); else renderNotFound(false);
    bindCommon();
    if (focusHeading) { const heading = document.querySelector<HTMLElement>('main h1'); if (heading) { heading.tabIndex = -1; heading.focus({ preventScroll: true }); routeStatus.textContent = heading.textContent ?? document.title; } }
  } catch (error) {
    storageError = error instanceof Error ? error.message : 'The ledger could not be loaded.'; setMeta('Storage error — Release Ledger', 'Release Ledger could not open browser storage.', location.pathname);
    app.innerHTML = shell(`<main id="main" class="legal"><p class="eyebrow">Storage error</p><h1>Your ledger could not open</h1><p>${escapeHtml(storageError)}</p><button class="button" type="button" id="retry">Try again</button></main>`);
    document.querySelector('#retry')?.addEventListener('click', () => { storageError = ''; void render(); }); bindCommon();
  }
}

async function renderHome(): Promise<void> {
  const [jobs, events, settings] = await Promise.all([getJobs(), getEvents(), getSettings()]);
  const active = jobs.filter(job => !job.archived); const archived = jobs.filter(job => job.archived); const totals = active.map(job => calculateTotals(job, events));
  const held = totals.filter(total => total.status === 'held').length; const ready = totals.filter(total => total.status === 'ready').length;
  setMeta(isDemoMode ? 'Demo — Release Ledger' : 'Release Ledger — know when work is safe to release', isDemoMode ? 'Try Release Ledger with isolated sample jobs and release decisions.' : 'Compare client payments with finished work before sending files. Built for freelancers who take deposits.', isDemoMode ? '/demo' : '/');
  const jobCards = active.map(job => { const total = calculateTotals(job, events); return `<li><a class="job-row route-link" href="${appPath(`/jobs/${encodeURIComponent(job.id)}`)}"><span class="status-orb ${total.status}" aria-hidden="true"></span><span class="job-row-main"><strong>${escapeHtml(job.name)}</strong><small>${escapeHtml(job.clientName || 'No client name')} · ${total.statusLabel}</small></span><span class="job-row-money"><strong>${escapeHtml(formatMoney(total.payable, job.currency))}</strong><small>still payable</small></span><span class="row-arrow">${icon('arrow')}</span></a></li>`; }).join('');
  const northstar = active.find(job => job.id === 'demo-brand');
  const northstarTotal = northstar ? calculateTotals(northstar, events) : undefined;
  const demoPreview = isDemoMode && northstar && northstarTotal ? `<section class="demo-preview" aria-labelledby="demo-preview-heading"><p class="eyebrow">Sample job</p><h2 id="demo-preview-heading">${escapeHtml(northstar.name)}</h2><a class="route-link" href="${appPath(`/jobs/${northstar.id}`)}"><span class="demo-preview-status"><span class="status-orb ${northstarTotal.status}" aria-hidden="true"></span>${escapeHtml(northstarTotal.statusLabel)}</span><strong>${escapeHtml(northstar.clientName)} · ${escapeHtml(formatMoney(northstarTotal.paid, northstar.currency))} received</strong><span>${escapeHtml(northstarTotal.statusReason)}</span><small>Latest entry: Identity files finished</small></a></section>` : '';

  app.innerHTML = shell(`<main id="main"><section class="hero ${isDemoMode ? 'demo-hero' : ''}" aria-labelledby="page-title"><div class="hero-copy"><p class="eyebrow">Compare payments with finished work</p><h1 id="page-title">${isDemoMode ? 'See release decisions with sample jobs' : 'Know when client work is safe to release'}</h1><p class="lede">${isDemoMode ? 'Three sample jobs show Ready, Review, and Hold results. Changes stay separate from your ledger.' : 'For freelancers taking deposits, compare payments with finished work before sending files.'}</p>${demoPreview}<div class="hero-actions">${isDemoMode ? `<a class="button primary route-link" href="${appPath('/jobs/demo-brand')}">Open the sample job ${icon('arrow')}</a><button class="button quiet" id="new-job" type="button">${icon('plus')} Create job</button>` : `<a class="button primary route-link" href="/demo">Try it with sample data</a><button class="button quiet" id="new-job" type="button">${icon('plus')} Create job</button>`}</div>${!isDemoMode ? '<p class="action-note">Sample jobs open now. Your ledger stays unchanged.</p>' : `<div class="demo-counts" aria-label="Sample release results"><span><strong>${ready}</strong> Ready</span><span><strong>${held}</strong> Hold</span><span><strong>${active.length - ready - held}</strong> Review</span></div>`}<ul class="plain-facts"><li>No account</li><li>Works offline after first visit</li><li>Data stays in this browser</li></ul></div><picture class="hero-art"><source media="(max-width: 640px)" srcset="/assets/threshold-garden-720.webp" /><img src="/assets/threshold-garden-1200.webp" width="1200" height="800" alt="Stepping stones lead through a brass gate toward a wrapped portfolio parcel." fetchpriority="high" decoding="async" /></picture></section>
  <section class="workspace" aria-labelledby="jobs-heading"><div class="section-heading"><div><p class="eyebrow">Your jobs</p><h2 id="jobs-heading">Active jobs</h2></div>${active.length ? `<div class="summary-strip"><span><strong>${ready}</strong> ready</span><span><strong>${held}</strong> held</span><span><strong>${active.length}</strong> total</span></div>` : ''}</div>${active.length ? `<ul class="job-list">${jobCards}</ul>` : `<div class="empty-state"><span class="empty-number" aria-hidden="true">01</span><div><h3>Create your first job</h3><p>Add the agreed total. Then record each payment and completed milestone.</p><button class="text-button" id="empty-new-job" type="button">Create your first job ${icon('arrow')}</button></div></div>`}${archived.length ? `<details class="archive"><summary>${archived.length} archived ${archived.length === 1 ? 'job' : 'jobs'}</summary><ul class="job-list compact">${archived.map(job => `<li><a class="job-row route-link" href="${appPath(`/jobs/${encodeURIComponent(job.id)}`)}"><span class="job-row-main"><strong>${escapeHtml(job.name)}</strong><small>${escapeHtml(job.clientName)}</small></span><span class="row-arrow">${icon('arrow')}</span></a></li>`).join('')}</ul></details>` : ''}</section>
  <section class="how-it-works" aria-labelledby="how-heading"><p class="eyebrow">How it works</p><h2 id="how-heading">Check release status in three steps</h2><ol><li><strong>Record payments</strong><span>Add deposits, balance payments, and refunds.</span></li><li><strong>Record finished work</strong><span>Add each completed milestone and its value.</span></li><li><strong>Check release status</strong><span>See Ready, Review, or Hold with the reason.</span></li></ol></section>
  <section class="limitations" aria-labelledby="limits-heading"><div><p class="eyebrow">What it does not do</p><h2 id="limits-heading">Limits and responsibilities</h2></div><div><p>Release Ledger records the amounts you enter. It does not hold funds, connect to a bank, process payments, or replace a contract.</p><p>Your release status depends on your entries. It cannot prevent a payment reversal or dispute.</p><a class="route-link" href="/privacy">Read how browser data is handled</a></div></section>
  <section class="ownership" aria-labelledby="ownership-heading"><div><p class="eyebrow">Export your records</p><h2 id="ownership-heading">Keep a backup</h2><p>Export all jobs and entries as JSON or CSV. Import a JSON backup when you need it.</p></div><div class="ownership-actions"><button class="button" id="export-json" type="button">${icon('download')} Export backup</button><button class="button quiet" id="export-csv" type="button">Export CSV</button><button class="button quiet" id="import-trigger" type="button">Import backup</button><input id="import-file" type="file" accept="application/json" hidden /></div></section>${jobDialog(settings)}</main>`);

  const openCreate = () => document.querySelector<HTMLDialogElement>('#job-dialog')?.showModal(); document.querySelector('#new-job')?.addEventListener('click', openCreate); document.querySelector('#empty-new-job')?.addEventListener('click', openCreate); bindDialog('#job-dialog');
  document.querySelector<HTMLFormElement>('#job-form')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const now = new Date().toISOString(); const job: Job = { id: crypto.randomUUID(), name: required(form, 'name'), clientName: textValue(form, 'clientName'), clientEmail: textValue(form, 'clientEmail'), totalAmount: numberValue(form, 'totalAmount'), currency: required(form, 'currency').toUpperCase(), taxLabel: textValue(form, 'taxLabel'), reference: textValue(form, 'reference'), receiptNote: '', archived: false, createdAt: now, updatedAt: now }; await saveJob(job); navigate(appPath(`/jobs/${job.id}`)); });
  document.querySelector('#export-json')?.addEventListener('click', () => void exportJson()); document.querySelector('#export-csv')?.addEventListener('click', () => void exportCsv()); document.querySelector('#import-trigger')?.addEventListener('click', () => document.querySelector<HTMLInputElement>('#import-file')?.click()); document.querySelector<HTMLInputElement>('#import-file')?.addEventListener('change', importFile);
}

function jobDialog(settings: AppSettings): string { return `<dialog id="job-dialog" aria-labelledby="job-dialog-title"><form method="dialog" class="dialog-card" id="job-form"><div class="dialog-heading"><div><p class="eyebrow">New job</p><h2 id="job-dialog-title">Create a job</h2></div><button class="icon-button dialog-close" type="button" aria-label="Close">×</button></div><p class="form-note">Required fields are marked with an asterisk.</p><div class="field"><label for="job-name">Job name <span aria-hidden="true">*</span></label><input id="job-name" name="name" required autocomplete="off" /></div><div class="two-fields"><div class="field"><label for="client-name">Client name</label><input id="client-name" name="clientName" autocomplete="name" /></div><div class="field"><label for="client-email">Client email</label><input id="client-email" type="email" name="clientEmail" autocomplete="email" /></div></div><div class="money-fields"><div class="field amount-field"><label for="total-amount">Agreed total <span aria-hidden="true">*</span></label><input id="total-amount" type="number" name="totalAmount" required min="0" max="${MAX_AMOUNT}" step="0.01" inputmode="decimal" aria-describedby="amount-limit" /><p class="field-help" id="amount-limit">Maximum ${MAX_AMOUNT.toLocaleString()}.</p></div><div class="field currency-field"><label for="currency">Currency</label><input id="currency" name="currency" value="USD" maxlength="3" pattern="[A-Za-z]{3}" required /></div><div class="field"><label for="tax-label">Tax label</label><input id="tax-label" name="taxLabel" value="Tax" /></div></div><div class="field"><label for="reference">Reference or PO</label><input id="reference" name="reference" /></div>${settings.businessName ? `<p class="form-note">Receipt business: ${escapeHtml(settings.businessName)}</p>` : ''}<p class="form-note">Amounts are records only. Release Ledger does not hold funds or process payments.</p><div class="dialog-actions"><button class="button quiet dialog-close" type="button">Cancel</button><button class="button primary" type="submit">Create job</button></div></form></dialog>`; }

async function renderJob(id: string): Promise<void> {
  const [job, events, settings] = await Promise.all([getJob(id), getEvents(id), getSettings()]);
  if (!job) { renderNotFound(true); return; }
  setMeta(`${job.name} — Release Ledger`, `Check payments, finished work, and release status for ${job.name}.`, appPath(`/jobs/${encodeURIComponent(id)}`));
  const total = calculateTotals(job, events);
  const rows = events.map(entry => `<li class="event-row"><span class="event-glyph type-${entry.type}" aria-hidden="true">${eventGlyph(entry.type)}</span><div class="event-copy"><strong>${eventLabels[entry.type]}</strong><span>${escapeHtml(entry.note || defaultEntryNote(entry))}${entry.decision ? ` · ${escapeHtml(entry.decision)}` : ''}</span></div><time datetime="${escapeHtml(entry.date)}">${formatDate(entry.date)}</time><strong class="event-amount">${entry.amount ? escapeHtml(formatMoney(entry.amount, job.currency)) : '—'}</strong></li>`).join('');
  app.innerHTML = shell(`<main id="main" class="job-page"><div class="crumb"><a class="route-link" href="${appPath('/')}">← All jobs</a><span>${escapeHtml(job.reference || 'No reference')}</span></div><section class="job-title"><div><p class="eyebrow">${job.archived ? 'Archived job' : 'Active job'}</p><h1>${escapeHtml(job.name)}</h1><p>${escapeHtml(job.clientName || 'Client not named')}${job.clientEmail ? ` · <a href="mailto:${escapeHtml(job.clientEmail)}">${escapeHtml(job.clientEmail)}</a>` : ''}</p></div><div class="job-actions"><a class="button quiet route-link" href="${appPath(`/receipt/${encodeURIComponent(job.id)}`)}">Client receipt</a><button class="button quiet" id="edit-job" type="button">Edit details</button></div></section>
  <section class="verdict ${total.status}" aria-labelledby="verdict-heading"><div class="verdict-mark"><span aria-hidden="true">${statusIcon(total.status)}</span><small>Release status</small></div><div><h2 id="verdict-heading">${total.statusLabel}</h2><p>${escapeHtml(total.statusReason)}</p></div><button class="button verdict-action" id="record-event" type="button">${icon('plus')} Record entry</button></section>
  <section class="balance-grid" aria-label="Job balances"><div><small>Payments received</small><strong>${escapeHtml(formatMoney(total.paid, job.currency))}</strong><span>Deposits + balance payments − refunds</span></div><div><small>Available for finished work</small><strong>${escapeHtml(formatMoney(total.available, job.currency))}</strong><span>Payments − work already sent</span></div><div><small>Still due</small><strong>${escapeHtml(formatMoney(total.payable, job.currency))}</strong><span>Agreed ${escapeHtml(formatMoney(job.totalAmount, job.currency))}</span></div><div><small>Finished work not sent</small><strong>${escapeHtml(formatMoney(total.pendingWork, job.currency))}</strong><span>Finished − sent</span></div></section>
  <section class="ledger-section" aria-labelledby="entries-heading"><div class="section-heading"><div><p class="eyebrow">Recorded history</p><h2 id="entries-heading">Ledger entries</h2></div><button class="text-button" id="record-event-secondary" type="button">Record entry ${icon('arrow')}</button></div>${events.length ? `<ol class="event-list">${rows}</ol>` : '<div class="ledger-empty"><p>No entries yet. Record a deposit or finished milestone to calculate release status.</p></div>'}</section>
  <section class="job-settings"><div><h2>Job controls</h2><p>${escapeHtml(job.taxLabel || 'Tax')} is your chosen label. Check every amount against the client agreement.</p></div><div><button class="button quiet" id="job-csv" type="button">Export this job</button><button class="button quiet" id="archive-job" type="button">${job.archived ? 'Restore job' : 'Archive job'}</button></div></section>${eventDialog(job)}${editJobDialog(job, settings)}</main>`);
  const openEntry = () => document.querySelector<HTMLDialogElement>('#event-dialog')?.showModal(); document.querySelector('#record-event')?.addEventListener('click', openEntry); document.querySelector('#record-event-secondary')?.addEventListener('click', openEntry); bindDialog('#event-dialog'); bindDialog('#edit-job-dialog'); bindEventForm(job);
  document.querySelector('#edit-job')?.addEventListener('click', () => document.querySelector<HTMLDialogElement>('#edit-job-dialog')?.showModal());
  document.querySelector<HTMLFormElement>('#edit-job-form')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); await saveJob({ ...job, name: required(form, 'name'), clientName: textValue(form, 'clientName'), clientEmail: textValue(form, 'clientEmail'), totalAmount: numberValue(form, 'totalAmount'), currency: required(form, 'currency').toUpperCase(), taxLabel: textValue(form, 'taxLabel'), reference: textValue(form, 'reference'), receiptNote: textValue(form, 'receiptNote'), updatedAt: new Date().toISOString() }); await render(); showToast('Job details saved.'); });
  document.querySelector('#archive-job')?.addEventListener('click', async () => { await saveJob({ ...job, archived: !job.archived, updatedAt: new Date().toISOString() }); await render(); showToast(job.archived ? 'Job restored.' : 'Job archived. You can restore it later.'); });
  document.querySelector('#job-csv')?.addEventListener('click', () => void exportCsv(job.id));
}

function eventDialog(job: Job): string { return `<dialog id="event-dialog" aria-labelledby="event-dialog-title"><form method="dialog" id="event-form" class="dialog-card"><div class="dialog-heading"><div><p class="eyebrow">${escapeHtml(job.name)}</p><h2 id="event-dialog-title">Record an entry</h2></div><button class="icon-button dialog-close" type="button" aria-label="Close">×</button></div><div class="field"><label for="event-type">Entry type</label><select id="event-type" name="type">${Object.entries(eventLabels).map(([value, label]) => `<option value="${value}">${label}</option>`).join('')}</select><p class="field-help" id="event-help">Money received at the start of the job.</p></div><div class="two-fields"><div class="field"><label for="event-amount">Amount (${escapeHtml(job.currency)})</label><input id="event-amount" type="number" name="amount" min="0" max="${MAX_AMOUNT}" step="0.01" inputmode="decimal" required /></div><div class="field"><label for="event-date">Date</label><input id="event-date" type="date" name="date" value="${new Date().toISOString().slice(0, 10)}" required /></div></div><fieldset id="decision-fields" hidden><legend>Release decision</legend><div class="decision-options"><label><input type="radio" name="decision" value="ready" /> Ready</label><label><input type="radio" name="decision" value="review" /> Review</label><label><input type="radio" name="decision" value="held" /> Hold</label></div><p class="field-help">Use amount 0 to record a decision without sending work.</p></fieldset><div class="field"><label for="event-note">Note</label><textarea id="event-note" name="note" rows="3" placeholder="What changed or what was agreed?"></textarea></div><p class="form-error" id="event-error" role="alert" aria-live="assertive"></p><div class="dialog-actions"><button class="button quiet dialog-close" type="button">Cancel</button><button class="button primary" type="submit">Save entry</button></div></form></dialog>`; }

function editJobDialog(job: Job, settings: AppSettings): string { return `<dialog id="edit-job-dialog" aria-labelledby="edit-job-title"><form method="dialog" id="edit-job-form" class="dialog-card"><div class="dialog-heading"><div><p class="eyebrow">Job settings</p><h2 id="edit-job-title">Edit details</h2></div><button class="icon-button dialog-close" type="button" aria-label="Close">×</button></div><div class="field"><label for="edit-name">Job name</label><input id="edit-name" name="name" value="${escapeHtml(job.name)}" required /></div><div class="two-fields"><div class="field"><label for="edit-client">Client name</label><input id="edit-client" name="clientName" value="${escapeHtml(job.clientName)}" /></div><div class="field"><label for="edit-email">Client email</label><input id="edit-email" type="email" name="clientEmail" value="${escapeHtml(job.clientEmail)}" /></div></div><div class="money-fields"><div class="field amount-field"><label for="edit-total">Agreed total</label><input id="edit-total" type="number" name="totalAmount" min="0" max="${MAX_AMOUNT}" step="0.01" value="${job.totalAmount}" required /></div><div class="field currency-field"><label for="edit-currency">Currency</label><input id="edit-currency" name="currency" maxlength="3" pattern="[A-Za-z]{3}" value="${escapeHtml(job.currency)}" required /></div><div class="field"><label for="edit-tax">Tax label</label><input id="edit-tax" name="taxLabel" value="${escapeHtml(job.taxLabel)}" /></div></div><div class="field"><label for="edit-reference">Reference or PO</label><input id="edit-reference" name="reference" value="${escapeHtml(job.reference)}" /></div><div class="field"><label for="receipt-note">Receipt note</label><textarea id="receipt-note" name="receiptNote" rows="3">${escapeHtml(job.receiptNote)}</textarea></div><div class="field"><label for="business-name">Business name</label><input id="business-name" value="${escapeHtml(settings.businessName)}" disabled /></div><div class="dialog-actions"><button class="button quiet dialog-close" type="button">Cancel</button><button class="button primary" type="submit">Save details</button></div></form></dialog>`; }

function bindEventForm(job: Job): void {
  const type = document.querySelector<HTMLSelectElement>('#event-type'); const decision = document.querySelector<HTMLElement>('#decision-fields'); const help = document.querySelector<HTMLElement>('#event-help'); const amount = document.querySelector<HTMLInputElement>('#event-amount');
  const helps: Record<EventType, string> = { deposit: 'Money received at the start of the job.', milestone: 'Value of work now finished.', release: 'Decision and value of work sent. Use 0 if nothing was sent.', refund: 'Money returned to the client.', balance: 'A balance payment from the client.' };
  const sync = () => { const selected = type?.value as EventType; if (help) help.textContent = helps[selected]; if (decision) decision.hidden = selected !== 'release'; if (amount) amount.min = selected === 'release' ? '0' : '0.01'; }; type?.addEventListener('change', sync); sync();
  document.querySelector<HTMLFormElement>('#event-form')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const selected = required(form, 'type') as EventType; const amountValue = numberValue(form, 'amount'); const decisionValue = form.get('decision') as ReleaseDecision | null; const error = document.querySelector<HTMLElement>('#event-error'); if (selected !== 'release' && amountValue <= 0) { if (error) error.textContent = 'Enter an amount greater than zero.'; return; } if (selected === 'release' && !decisionValue) { if (error) error.textContent = 'Choose the release decision you made.'; return; } const entry: LedgerEvent = { id: crypto.randomUUID(), jobId: job.id, type: selected, amount: amountValue, date: required(form, 'date'), note: textValue(form, 'note'), decision: selected === 'release' ? decisionValue ?? undefined : undefined, createdAt: new Date().toISOString() }; await saveEvent(entry); await saveJob({ ...job, updatedAt: new Date().toISOString() }); await render(); showToast(`${eventLabels[selected]} recorded.`); });
}

async function renderReceipt(id: string): Promise<void> {
  const [job, events, settings] = await Promise.all([getJob(id), getEvents(id), getSettings()]); if (!job) { renderNotFound(true); return; }
  setMeta(`Receipt for ${job.name} — Release Ledger`, `Client receipt for ${job.name}.`, appPath(`/receipt/${encodeURIComponent(id)}`)); const total = calculateTotals(job, events);
  app.innerHTML = shell(`<main id="main" class="receipt-page"><div class="receipt-toolbar"><a class="route-link" href="${appPath(`/jobs/${encodeURIComponent(job.id)}`)}">← Back to job</a><button class="button primary" id="print-receipt" type="button">Print or save PDF</button></div><article class="receipt-sheet"><header><div><p class="eyebrow">Client receipt</p><h1>${escapeHtml(job.name)}</h1><p>Prepared for ${escapeHtml(job.clientName || 'client')}</p></div><div class="receipt-brand"><span>${icon('gate')}</span><strong>${escapeHtml(settings.businessName || 'Release Ledger')}</strong></div></header><dl class="receipt-meta"><div><dt>Reference</dt><dd>${escapeHtml(job.reference || '—')}</dd></div><div><dt>Issued</dt><dd>${formatDate(new Date().toISOString().slice(0, 10))}</dd></div><div><dt>Currency</dt><dd>${escapeHtml(job.currency)}</dd></div><div><dt>${escapeHtml(job.taxLabel || 'Tax')}</dt><dd>Included as agreed</dd></div></dl><section class="receipt-total"><div><small>Payments received after refunds</small><strong>${escapeHtml(formatMoney(total.paid, job.currency))}</strong></div><div><small>Remaining on agreed total</small><strong>${escapeHtml(formatMoney(total.payable, job.currency))}</strong></div></section><section><h2>Entries</h2><table><thead><tr><th>Date</th><th>Entry</th><th>Note</th><th>Amount</th></tr></thead><tbody>${events.map(entry => `<tr><td>${formatDate(entry.date)}</td><td>${eventLabels[entry.type]}</td><td>${escapeHtml(entry.note || defaultEntryNote(entry))}</td><td>${entry.amount ? escapeHtml(formatMoney(entry.amount, job.currency)) : '—'}</td></tr>`).join('') || '<tr><td colspan="4">No entries recorded.</td></tr>'}</tbody></table></section>${job.receiptNote ? `<p class="receipt-note">${escapeHtml(job.receiptNote)}</p>` : ''}<footer><p>This receipt reports entries from the service provider. Release Ledger does not process or hold funds.</p><p>Generated in this browser · ${escapeHtml(location.host || 'Release Ledger')}</p></footer></article></main>`);
  document.querySelector('#print-receipt')?.addEventListener('click', () => window.print());
}
function renderPrivacy(): void { setMeta('Privacy — Release Ledger', 'How Release Ledger stores job data in your browser.', '/privacy'); app.innerHTML = shell(`<main id="main" class="legal"><p class="eyebrow">Privacy</p><h1>Control the job data in your browser</h1><p class="lede">Release Ledger stores job details on this device. No account is required.</p><h2>Data stored here</h2><p>This browser stores jobs, client details, amounts, notes, and settings. Demo data uses a separate browser database.</p><h2>Data sent elsewhere</h2><p>The app does not send ledger data to a server. It has no analytics, advertising, bank connection, or online ledger copy.</p><h2>Your control</h2><p>Export a JSON backup before clearing browser data. Clear this site’s browser data to remove the ledger from this device.</p><p class="legal-date">Effective 28 August 2026 · <a class="route-link" href="/">Return to jobs</a></p></main>`); }
function renderTerms(): void { setMeta('Terms — Release Ledger', 'Terms for using Release Ledger as a local job record.', '/terms'); app.innerHTML = shell(`<main id="main" class="legal"><p class="eyebrow">Terms</p><h1>Use this as a record, not escrow</h1><p class="lede">Release Ledger documents your entries and decisions. It does not provide payment, legal, accounting, collection, or escrow services.</p><h2>Your responsibility</h2><p>Check every entry against your contract and payment records. Release status reflects only the values you enter.</p><h2>Limits</h2><p>A Ready result cannot guarantee that a payment will not be reversed or disputed. The software is provided “as is,” where law permits.</p><h2>Acceptable use</h2><p>Do not misrepresent payments, impersonate an escrow provider, or create deceptive receipts.</p><p class="legal-date">Effective 28 August 2026 · <a class="route-link" href="/privacy">Read privacy</a></p></main>`); }
function renderNotFound(missingJob: boolean): void { setMeta('Page not found — Release Ledger', 'This Release Ledger page does not exist.', '/404'); app.innerHTML = shell(`<main id="main" class="legal not-found"><p class="eyebrow">404 · Not found</p><h1>${missingJob ? 'That job is not in this browser' : 'This page is not in the ledger'}</h1><p>${missingJob ? 'It may be in another browser or backup.' : 'Check the address or return to your jobs.'}</p><a class="button primary route-link" href="${appPath('/')}">Return to jobs</a></main>`); }

function bindCommon(): void {
  document.querySelectorAll<HTMLAnchorElement>('a.route-link').forEach(link => link.addEventListener('click', event => { if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey || link.origin !== location.origin) return; const path = `${link.pathname}${link.search}`; if (isDemoPath(path) !== isDemoMode) return; event.preventDefault(); navigate(path); }));
  document.querySelector('#theme-toggle')?.addEventListener('click', () => { const dark = document.documentElement.dataset.theme === 'dark' || (!document.documentElement.dataset.theme && matchMedia('(prefers-color-scheme: dark)').matches); document.documentElement.dataset.theme = dark ? 'light' : 'dark'; if (!isDemoMode) localStorage.setItem('release-ledger-theme', dark ? 'light' : 'dark'); });
  document.querySelector('#reset-demo')?.addEventListener('click', async () => { await seedDemo(true); await render(); showToast('Demo reset to the original sample jobs.'); });
  document.querySelector('#start-real')?.addEventListener('click', async () => { await discardDemo(); location.assign('/'); });
}
function bindDialog(selector: string): void { const dialog = document.querySelector<HTMLDialogElement>(selector); dialog?.querySelectorAll('.dialog-close').forEach(button => button.addEventListener('click', () => dialog.close())); dialog?.addEventListener('click', event => { if (event.target === dialog) dialog.close(); }); }
function required(form: FormData, key: string): string { const value = textValue(form, key); if (!value) throw new Error(`Complete the ${key} field.`); return value; }
function textValue(form: FormData, key: string): string { return String(form.get(key) ?? '').trim(); }
function numberValue(form: FormData, key: string): number { const value = Number(form.get(key)); const rounded = Math.round(value * 100) / 100; if (!Number.isFinite(value) || !Number.isFinite(rounded) || value < 0 || rounded > MAX_AMOUNT) throw new Error(`Enter an amount from 0 to ${MAX_AMOUNT.toLocaleString()}.`); return rounded; }
function formatDate(date: string): string { return new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date.slice(0, 10)}T12:00:00Z`)); }
function defaultEntryNote(entry: LedgerEvent): string { return entry.type === 'release' ? 'Release decision recorded' : 'No note'; }
function eventGlyph(type: EventType): string { return ({ deposit: '+', balance: '+', milestone: '◇', release: '→', refund: '−' } as const)[type]; }
function statusIcon(status: ReleaseDecision): string { return status === 'ready' ? '✓' : status === 'held' ? '!' : '…'; }
function navigate(path: string): void { history.pushState({}, '', path); window.scrollTo(0, 0); void render(true); }
function showToast(message: string): void { window.clearTimeout(toastTimer); toast.textContent = message; toast.classList.add('visible'); toastTimer = window.setTimeout(() => toast.classList.remove('visible'), 3600); }
function download(name: string, content: string, type: string): void { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function exportJson(): Promise<void> { download(`release-ledger-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(await createBackup(), null, 2), 'application/json'); showToast('Backup exported.'); }
async function exportCsv(jobId?: string): Promise<void> { const [jobs, events] = await Promise.all([getJobs(), getEvents()]); const relevantJobs = jobId ? jobs.filter(job => job.id === jobId) : jobs; const ids = new Set(relevantJobs.map(job => job.id)); const header = ['Job', 'Client', 'Reference', 'Currency', 'Agreed total', 'Date', 'Entry', 'Amount', 'Decision', 'Note']; const rows = events.filter(entry => ids.has(entry.jobId)).map(entry => { const job = relevantJobs.find(item => item.id === entry.jobId)!; return [job.name, job.clientName, job.reference, job.currency, job.totalAmount, entry.date, eventLabels[entry.type], entry.amount, entry.decision ?? '', entry.note]; }); download(`release-ledger${jobId ? '-job' : ''}.csv`, rowsToCsv([header, ...rows]), 'text/csv;charset=utf-8'); showToast('CSV exported.'); }
async function importFile(event: Event): Promise<void> { const input = event.currentTarget as HTMLInputElement; const file = input.files?.[0]; if (!file) return; try { const result = await importBackup(JSON.parse(await file.text())); await render(); showToast(`Imported ${result.jobs} jobs and ${result.events} entries.`); } catch (error) { showToast(error instanceof Error ? error.message : 'Import failed. No records were changed.'); } finally { input.value = ''; } }

function applyTheme(): void { if (isDemoMode) return; const saved = localStorage.getItem('release-ledger-theme'); if (saved === 'dark' || saved === 'light') document.documentElement.dataset.theme = saved; }
applyTheme();
if (isDemoMode && location.pathname === '/' && new URLSearchParams(location.search).get('demo') === '1') history.replaceState({}, '', '/demo');
window.addEventListener('popstate', () => void render(true));
window.addEventListener('online', () => { const banner = document.querySelector<HTMLElement>('#network-banner'); if (banner) banner.hidden = true; showToast('Back online.'); });
window.addEventListener('offline', () => { const banner = document.querySelector<HTMLElement>('#network-banner'); if (banner) banner.hidden = false; });
if ('serviceWorker' in navigator) window.addEventListener('load', () => { navigator.serviceWorker.register('/sw.js').then(registration => registration.addEventListener('updatefound', () => { const worker = registration.installing; worker?.addEventListener('statechange', () => { if (worker.state === 'installed' && navigator.serviceWorker.controller) showToast('An update is ready. Reload to use it.'); }); })).catch(() => { /* The ledger still works online without installation. */ }); });
void render();
